  
  
CREATE DATABASE Users
CREATE TABLE [dbo].[RegisterUser](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](500) NOT NULL,
 CONSTRAINT [PK_RegisterUser] PRIMARY KEY CLUSTERED )
 USE [master]
GO
/****** Object:  Database [LoginRegistrationInMVC]    Script Date: 7/16/2018 7:45:32 PM ******/

ALTER DATABASE [Users] SET COMPATIBILITY_LEVEL = 110
GO

ALTER DATABASE [LoginRegistrationInMVC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET ARITHABORT OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET  MULTI_USER 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET PAGE_VERIFY 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LoginRegistrationInMVC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [LoginRegistrationInMVC]
GO
/****** Object:  Table [dbo].[RegisterUser]    Script Date: 7/16/2018 7:45:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON

GO
SET ANSI_PADDING OFF
GO
S


ALTER DATABASE [LoginRegistrationInMVC] SET  READ_WRITE 
GO